### ISSUE TITLE
cgcloud requests old version of bd2k-python-lib

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/cgcloud#133]
I think I've seen this issue before - is there a way the code can request versions >= version.number instead of == ?

`cgcloud -h` dies with

```
Traceback (most recent call last):
  File "/home/ubuntu/cgcloud/bin/cgcloud", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/ubuntu/cgcloud/local/lib/python2.7/site-packages/pkg_resources.py", line 2720, in <module>
    parse_requirements(__requires__), Environment()
  File "/home/ubuntu/cgcloud/local/lib/python2.7/site-packages/pkg_resources.py", line 588, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: bd2k-python-lib==1.11.dev6
```

`pip list`

```
argparse (1.2.1)
bd2k-python-lib (1.13.dev16)
boto (2.38.0)
cgcloud-core (1.3.7)
cgcloud-jenkins (1.3.7)
cgcloud-lib (1.3.7)
cgcloud-mesos (1.3.7)
cgcloud-toil (1.3.7)
ecdsa (0.13)
Fabric (1.10.2)
paramiko (1.16.0)
pip (1.5.4)
pycrypto (2.6.1)
pycurl (7.43.0)
PyYAML (3.11)
s3am (1.0b1.dev63)
setuptools (2.2)
wsgiref (0.1.2)
```

The reason I have a later version of bd2k-lib is because `pip install s3am --pre` pulls it.

**Comment by hannes-ucsc** [comment]
> The reason I have a later version of bd2k-lib is because pip install s3am --pre pulls it.

Exactly. That's why we use virtualenv's. We need to isolate each program into its own virtualenv such that we can avoid conflicting dependency versions. Pip will happily ignore conflicting dependency versions and just chose one version arbitrarily. That approach will likely break all but one of the programs in the virtualenv.

So the solution is to use separate virtualenvs. One for s3am and one for cgcloud.
