### ISSUE TITLE
spark version

### ISSUE THREAD

**Issue by ayat-rashad** [BD2KGenomics/cgcloud#169]
when I check spark version I get 1.2 
Is it possible to control spark version before creating the image?

**Comment by hannes-ucsc** [comment]
Not without modifying the source. The reason the version is not user-configurable is that different Spark versions may have different dependencies (e.g. Hadoop version) and different installation procedures. In the best case (and depending on the specific Spark version) you just need to modify a single line of code, otherwise you'd have to touch more. The master branch of cgcloud deploys Spark 1.5.x BTW, so you could try that. To do so, either reinstall the unstable release by passing `--pre --upgrade` to pip OR clone the repo and follow the "[If you are a developer, ](https://github.com/BD2KGenomics/cgcloud#where-to-go-from-here)" from the README.
